[2022-11-24T13:01:21.041+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.load_landing_table scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2022-11-24T13:01:21.054+1300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: load_kpi_view_dag.load_landing_table scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2022-11-24T13:01:21.054+1300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T13:01:21.054+1300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-24T13:01:21.054+1300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T13:01:21.066+1300] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): load_landing_table> on 2022-11-23 00:00:00+00:00
[2022-11-24T13:01:21.074+1300] {standard_task_runner.py:55} INFO - Started process 56409 to run task
[2022-11-24T13:01:21.079+1300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'load_kpi_view_dag', 'load_landing_table', 'scheduled__2022-11-23T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/load_kpi_view.py', '--cfg-path', '/var/folders/xc/5xlsywvn2n5d0_ty56lp12y80000gp/T/tmpnujamlbv']
[2022-11-24T13:01:21.081+1300] {standard_task_runner.py:83} INFO - Job 46: Subtask load_landing_table
[2022-11-24T13:01:21.255+1300] {task_command.py:376} INFO - Running <TaskInstance: load_kpi_view_dag.load_landing_table scheduled__2022-11-23T00:00:00+00:00 [running]> on host macbook-pro.hq.optimalbi.site
[2022-11-24T13:01:21.336+1300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_kpi_view_dag
AIRFLOW_CTX_TASK_ID=load_landing_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-23T00:00:00+00:00
[2022-11-24T13:01:21.354+1300] {base.py:71} INFO - Using connection ID 'postgres_db' for task execution.
[2022-11-24T13:01:21.364+1300] {sql.py:315} INFO - Running statement: 

--CREATE OR REPLACE PROCEDURE logs.scan_csvs(varchar[]) AS $$
do $$
<<first_block>>

DECLARE x varchar(500);
BEGIN
  --FOREACH x IN ARRAY array[['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_2.csv'], ['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_3.csv'], ['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_1.csv']]
  FOREACH x IN ARRAY array[['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_2.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_3.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_1.csv']]
  LOOP
    RAISE NOTICE 'row = %', x;
    EXECUTE format(
        COPY logs.landing_table("site", "start_timestamp", "end_timestamp")
        FROM x
        DELIMITER ','
        CSV HEADER
    )
   
  END LOOP;
END  first_block $$;
--$$ LANGUAGE plpgsql;




--logs.scan_csvs(['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_2.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_3.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_1.csv'])
--DECLARE vSite varchar;
--vSite := SELECT scan_csvs(ARRAY[['/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_2.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_3.csv', '/Users/hirenpatel/airflow/csv_batch_files/task_1_logs_batch_1.csv']]);

--SELECT string_to_array(returned_csvs, ',') AS split_csvs;
, parameters: None
[2022-11-24T13:01:21.447+1300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "logs"
LINE 14:         COPY logs.landing_table("site", "start_timestamp", "...
                      ^

[2022-11-24T13:01:21.496+1300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=load_kpi_view_dag, task_id=load_landing_table, execution_date=20221123T000000, start_date=20221124T000121, end_date=20221124T000121
[2022-11-24T13:01:21.509+1300] {standard_task_runner.py:100} ERROR - Failed to execute job 46 for task load_landing_table (syntax error at or near "logs"
LINE 14:         COPY logs.landing_table("site", "start_timestamp", "...
                      ^
; 56409)
[2022-11-24T13:01:21.545+1300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-24T13:01:21.627+1300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
